# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: true
AddContributionDocs: true
AddCopierCI: true
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: true
AddGitHubTemplates: true
AddLintCI: true
AddLychee: true
AddMacToCI: true
AddPrecommit: true
AddPrecommitUpdateCI: true
AddTagBotCI: true
AddTestCI: true
AddWinToCI: true
Authors: singularitti <singularitti@outlook.com>
CheckExplicitImports: true
CodeOfConductContact: singularitti@outlook.com
ConfigIndentation: 2
ExplicitImportsChecklist: exclude_all_qualified_accesses_are_public
GitHubActionVersionAutoUpdate: dependabot
JuliaCompatAutoUpdate: dependabot
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: singularitti
MarkdownIndentation: 2
PackageName: DirWorkflow
PackageOwner: singularitti
PackageUUID: af77908b-fbd1-5c81-abc0-13a9534196fe
RunJuliaNightlyOnCI: true
StrategyConfirmIncluded: true
StrategyLevel: 3
StrategyReviewExcluded: true
TestingStrategy: testitem_basic
UseCirrusCI: true
_src_path: /Users/qz/.julia/packages/BestieTemplate/fOzc4
